development:
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || 'mysql2://root:password1@db:3306/lostandfound-dev' %>

production:
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

test:
  url: <%= ENV['DATABASE_URL'] || 'mysql2://root:password1@db:3306/lostandfound-test' %>
