development:
  pool: 5
  timeout: 5000
  adapter: mysql2
  user: root
  database: rails_dev

production:
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: sqlite3
  database: db/test.sqlite3
  # url: mysql2://root:root@db:3306/itemsdata
