development:
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || 'mysql2://root:root@db:3306/lostandfound-dev' %>

test:
  url: <%= ENV['DATABASE_URL'] || 'mysql2://root:root@db:3306/lostandfound-test' %>

production:
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || 'mysql2://root:root@db:3306/lostandfound-prod' %>

