development:
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/lostandfound-dev' %>

test:
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/lostandfound-test' %>

production:
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/lostandfound' %>
