development:
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/lostandfound-dev?pool=5' %>

test:
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/lostandfound-test?pool=5' %>

production:
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || 'postgres://root:root@db/lostandfound-prod' %>
