default: &default
  adapter: mysql2

development:
  pool: 5
  timeout: 5000
  url: mysql2://root:root@db:3306/itemsdata

production:
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

test:
  pool: 5
  timeout: 5000
  url: mysql2://root:root@db:3306/itemsdata_test
