development:
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || 'mysql2://root:TheGhostKingLives!@127.0.0.1:3306/LandF_development' %>

production:
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || 'mysql2://root:TheGhostKingLives!@127.0.0.1:3306/LandF_development' %>

  test:
    url: <%= ENV['DATABASE_URL'] || 'mysql2://root:TheGhostKingLives!@127.0.0.1:3306/LandF_development' %>